package Frontera;

import DAO.CostoDAO;
import Entidad.Costo;

public class VerCosto extends javax.swing.JPanel {

    private final CostoDAO daoCos = new CostoDAO();

    public VerCosto() {
        initComponents();
    }

    public void verCosto() {
        tableCos.setModel(daoCos.ver());
    }
    
        public Costo editarCosto() {
        Costo costo = new Costo();

        int rowSel = tableCos.getSelectedRow();
        if (rowSel >= 0) {
            
            costo.setEstado(Boolean.valueOf(tableCos.getValueAt(rowSel, 2).toString()));
            costo.setCostoAdi(tableCos.getValueAt(rowSel, 3).toString());
            costo.setCosto(Integer.valueOf(tableCos.getValueAt(rowSel, 4).toString()));
        }
        return costo;
    }


    public int fila() {
        int rowSel = tableCos.getSelectedRow();
        if (rowSel >= 0) {
            return Integer.parseInt(tableCos.getValueAt(rowSel, 0).toString());
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCos = new javax.swing.JTable();

        setBackground(new java.awt.Color(164, 186, 191));

        tableCos.setBackground(new java.awt.Color(36, 56, 63));
        tableCos.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        tableCos.setForeground(new java.awt.Color(192, 212, 216));
        tableCos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableCos.setToolTipText("");
        tableCos.setGridColor(new java.awt.Color(36, 56, 63));
        tableCos.setSelectionBackground(new java.awt.Color(164, 186, 191));
        tableCos.setSelectionForeground(new java.awt.Color(36, 56, 63));
        jScrollPane1.setViewportView(tableCos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCos;
    // End of variables declaration//GEN-END:variables
}
